# Generated by Django 4.1.3 on 2022-11-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="economiclessons", name="leaf_length",),
    ]
