# Generated by Django 4.1.3 on 2022-11-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_economiclessons_leaf_length"),
    ]

    operations = [
        migrations.RenameField(
            model_name="economiclessons", old_name="genre", new_name="info",
        ),
        migrations.RemoveField(model_name="economiclessons", name="difficulty",),
        migrations.RemoveField(model_name="economiclessons", name="keyword",),
        migrations.RemoveField(model_name="economiclessons", name="picture",),
    ]
